# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/user/tengbo/software/cmake-3-30/bin/cmake

# The command to remove a file.
RM = /home/user/tengbo/software/cmake-3-30/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/tengbo/bishe/phasing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/tengbo/bishe/phasing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/user/tengbo/software/cmake-3-30/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/user/tengbo/software/cmake-3-30/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/tengbo/bishe/phasing/CMakeFiles /home/user/tengbo/bishe/phasing//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/tengbo/bishe/phasing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tphase

# Build rule for target.
tphase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tphase
.PHONY : tphase

# fast build rule for target.
tphase/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/build
.PHONY : tphase/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/main.cpp.s
.PHONY : main.cpp.s

src/data_reader.o: src/data_reader.cpp.o
.PHONY : src/data_reader.o

# target to build an object file
src/data_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/src/data_reader.cpp.o
.PHONY : src/data_reader.cpp.o

src/data_reader.i: src/data_reader.cpp.i
.PHONY : src/data_reader.i

# target to preprocess a source file
src/data_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/src/data_reader.cpp.i
.PHONY : src/data_reader.cpp.i

src/data_reader.s: src/data_reader.cpp.s
.PHONY : src/data_reader.s

# target to generate assembly for a file
src/data_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/src/data_reader.cpp.s
.PHONY : src/data_reader.cpp.s

src/group.o: src/group.cpp.o
.PHONY : src/group.o

# target to build an object file
src/group.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/src/group.cpp.o
.PHONY : src/group.cpp.o

src/group.i: src/group.cpp.i
.PHONY : src/group.i

# target to preprocess a source file
src/group.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/src/group.cpp.i
.PHONY : src/group.cpp.i

src/group.s: src/group.cpp.s
.PHONY : src/group.s

# target to generate assembly for a file
src/group.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/src/group.cpp.s
.PHONY : src/group.cpp.s

src/realignment.o: src/realignment.cpp.o
.PHONY : src/realignment.o

# target to build an object file
src/realignment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/src/realignment.cpp.o
.PHONY : src/realignment.cpp.o

src/realignment.i: src/realignment.cpp.i
.PHONY : src/realignment.i

# target to preprocess a source file
src/realignment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/src/realignment.cpp.i
.PHONY : src/realignment.cpp.i

src/realignment.s: src/realignment.cpp.s
.PHONY : src/realignment.s

# target to generate assembly for a file
src/realignment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tphase.dir/build.make CMakeFiles/tphase.dir/src/realignment.cpp.s
.PHONY : src/realignment.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tphase"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/data_reader.o"
	@echo "... src/data_reader.i"
	@echo "... src/data_reader.s"
	@echo "... src/group.o"
	@echo "... src/group.i"
	@echo "... src/group.s"
	@echo "... src/realignment.o"
	@echo "... src/realignment.i"
	@echo "... src/realignment.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

